# Generated by Django 4.0.2 on 2022-02-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='userId',
            field=models.IntegerField(default=0),
        ),
    ]
