# Generated by Django 4.0.2 on 2022-02-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_article_body_alter_article_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('userId', models.IntegerField(default=0)),
                ('id', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
