# Generated by Django 4.0.2 on 2022-02-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_delete_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
